
package Vista;

import Controlador.AB_Empleado;
import Modelo.Empleado;
import java.io.IOException;
import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class F_Empleado3597 extends javax.swing.JFrame {


    private ArrayList<Empleado> E = new ArrayList();
    AB_Empleado ab_Empleado;
    
    public F_Empleado3597(){
        initComponents();
        
        txCodigo.requestFocus();
        
        ab_Empleado = new AB_Empleado();
        ab_Empleado.A_CrearEmpleado();
        
        try {
              ab_Empleado.SalvarA_Empleado();
        } catch (IOException | ClassNotFoundException ex) {
            Logger.getLogger(F_Empleado3597.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        TableData();
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);        
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        lbTitle = new javax.swing.JLabel();
        lbCodigo = new javax.swing.JLabel();
        txCodigo = new javax.swing.JTextField();
        sCodigo = new javax.swing.JSeparator();
        lbNombre = new javax.swing.JLabel();
        txNombre = new javax.swing.JTextField();
        sNombre = new javax.swing.JSeparator();
        lbDPI = new javax.swing.JLabel();
        txDPI = new javax.swing.JTextField();
        sDPI = new javax.swing.JSeparator();
        lbDireccion = new javax.swing.JLabel();
        txDireccion = new javax.swing.JTextField();
        sDireccion = new javax.swing.JSeparator();
        lbTelefono = new javax.swing.JLabel();
        txTelefono = new javax.swing.JTextField();
        sTelefono = new javax.swing.JSeparator();
        bttReporte = new javax.swing.JButton();
        bttBuscar = new javax.swing.JButton();
        bttGuardar = new javax.swing.JButton();
        bttAgregar1 = new javax.swing.JButton();
        bttModificar1 = new javax.swing.JButton();
        bttEliminar1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaEmpleado = new javax.swing.JTable();
        bttLimpiar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jta_Empleado = new javax.swing.JTextArea();
        txEdad = new javax.swing.JTextField();
        lbEdad = new javax.swing.JLabel();
        lbApellido = new javax.swing.JLabel();
        txApellido = new javax.swing.JTextField();
        lbPuesto = new javax.swing.JLabel();
        lbSalario = new javax.swing.JLabel();
        txSalario = new javax.swing.JTextField();
        lbID = new javax.swing.JLabel();
        lbCodID = new javax.swing.JLabel();
        cboxPuesto = new javax.swing.JComboBox<>();
        sTelefono1 = new javax.swing.JSeparator();
        sTelefono2 = new javax.swing.JSeparator();
        sDPI1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setMinimumSize(new java.awt.Dimension(700, 700));
        background.setPreferredSize(new java.awt.Dimension(700, 700));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitle.setBackground(new java.awt.Color(255, 255, 255));
        lbTitle.setFont(new java.awt.Font("Ebrima", 1, 30)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(51, 0, 51));
        lbTitle.setText("EMPLEADO");
        background.add(lbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 190, 40));

        lbCodigo.setBackground(new java.awt.Color(255, 255, 255));
        lbCodigo.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbCodigo.setForeground(new java.awt.Color(51, 0, 51));
        lbCodigo.setText("Código: ");
        background.add(lbCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        txCodigo.setBackground(new java.awt.Color(255, 255, 255));
        txCodigo.setForeground(new java.awt.Color(0, 0, 0));
        txCodigo.setBorder(null);
        txCodigo.setSelectionColor(new java.awt.Color(204, 204, 255));
        background.add(txCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 180, -1));
        background.add(sCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 160, 15));

        lbNombre.setBackground(new java.awt.Color(255, 255, 255));
        lbNombre.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbNombre.setForeground(new java.awt.Color(51, 0, 51));
        lbNombre.setText("Nombre:");
        background.add(lbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        txNombre.setBackground(new java.awt.Color(255, 255, 255));
        txNombre.setForeground(new java.awt.Color(0, 0, 0));
        txNombre.setBorder(null);
        txNombre.setSelectionColor(new java.awt.Color(204, 204, 255));
        background.add(txNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 183, -1));
        background.add(sNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 161, 15));

        lbDPI.setBackground(new java.awt.Color(255, 255, 255));
        lbDPI.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbDPI.setForeground(new java.awt.Color(51, 0, 51));
        lbDPI.setText("DPI:");
        background.add(lbDPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        txDPI.setBackground(new java.awt.Color(255, 255, 255));
        txDPI.setForeground(new java.awt.Color(0, 0, 0));
        txDPI.setBorder(null);
        txDPI.setSelectionColor(new java.awt.Color(204, 204, 255));
        background.add(txDPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 183, -1));
        background.add(sDPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 161, 15));

        lbDireccion.setBackground(new java.awt.Color(255, 255, 255));
        lbDireccion.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbDireccion.setForeground(new java.awt.Color(51, 0, 51));
        lbDireccion.setText("Dirección:");
        background.add(lbDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        txDireccion.setBackground(new java.awt.Color(255, 255, 255));
        txDireccion.setForeground(new java.awt.Color(0, 0, 0));
        txDireccion.setBorder(null);
        txDireccion.setSelectionColor(new java.awt.Color(204, 204, 255));
        background.add(txDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 183, -1));
        background.add(sDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 161, 15));

        lbTelefono.setBackground(new java.awt.Color(255, 255, 255));
        lbTelefono.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbTelefono.setForeground(new java.awt.Color(51, 0, 51));
        lbTelefono.setText("Teléfono:");
        background.add(lbTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        txTelefono.setBackground(new java.awt.Color(255, 255, 255));
        txTelefono.setForeground(new java.awt.Color(0, 0, 0));
        txTelefono.setBorder(null);
        txTelefono.setSelectionColor(new java.awt.Color(204, 204, 255));
        background.add(txTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 183, -1));
        background.add(sTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 161, 20));

        bttReporte.setBackground(new java.awt.Color(102, 0, 102));
        bttReporte.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        bttReporte.setForeground(new java.awt.Color(204, 204, 204));
        bttReporte.setText("Reporte");
        bttReporte.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttReporteActionPerformed(evt);
            }
        });
        background.add(bttReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 450, 110, 30));

        bttBuscar.setBackground(new java.awt.Color(102, 0, 102));
        bttBuscar.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        bttBuscar.setForeground(new java.awt.Color(204, 204, 204));
        bttBuscar.setText("Buscar");
        bttBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttBuscarActionPerformed(evt);
            }
        });
        background.add(bttBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 520, 110, 30));

        bttGuardar.setBackground(new java.awt.Color(153, 0, 0));
        bttGuardar.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        bttGuardar.setForeground(new java.awt.Color(204, 204, 204));
        bttGuardar.setText("GUARDAR CAMBIOS");
        bttGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttGuardarActionPerformed(evt);
            }
        });
        background.add(bttGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 30, 140, 30));

        bttAgregar1.setBackground(new java.awt.Color(102, 0, 102));
        bttAgregar1.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        bttAgregar1.setForeground(new java.awt.Color(204, 204, 204));
        bttAgregar1.setText("Agregar");
        bttAgregar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAgregar1ActionPerformed(evt);
            }
        });
        background.add(bttAgregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 110, 30));

        bttModificar1.setBackground(new java.awt.Color(102, 0, 102));
        bttModificar1.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        bttModificar1.setForeground(new java.awt.Color(204, 204, 204));
        bttModificar1.setText("Modificar");
        bttModificar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttModificar1ActionPerformed(evt);
            }
        });
        background.add(bttModificar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 110, 30));

        bttEliminar1.setBackground(new java.awt.Color(102, 0, 102));
        bttEliminar1.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        bttEliminar1.setForeground(new java.awt.Color(204, 204, 204));
        bttEliminar1.setText("Eliminar");
        bttEliminar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttEliminar1ActionPerformed(evt);
            }
        });
        background.add(bttEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, 110, 30));

        TablaEmpleado.setBackground(new java.awt.Color(255, 255, 255));
        TablaEmpleado.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        TablaEmpleado.setForeground(new java.awt.Color(51, 0, 51));
        TablaEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód", "Nombre", "Apellido", "DPI", "Dirección", "Edad", "Teléfono", "Salario", "ID", "Puesto"
            }
        ));
        TablaEmpleado.setGridColor(new java.awt.Color(0, 0, 0));
        TablaEmpleado.setSelectionBackground(new java.awt.Color(102, 0, 102));
        TablaEmpleado.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(TablaEmpleado);
        if (TablaEmpleado.getColumnModel().getColumnCount() > 0) {
            TablaEmpleado.getColumnModel().getColumn(0).setMinWidth(30);
            TablaEmpleado.getColumnModel().getColumn(0).setPreferredWidth(30);
            TablaEmpleado.getColumnModel().getColumn(0).setMaxWidth(30);
            TablaEmpleado.getColumnModel().getColumn(5).setMinWidth(40);
            TablaEmpleado.getColumnModel().getColumn(5).setPreferredWidth(40);
            TablaEmpleado.getColumnModel().getColumn(5).setMaxWidth(40);
            TablaEmpleado.getColumnModel().getColumn(8).setMinWidth(30);
            TablaEmpleado.getColumnModel().getColumn(8).setPreferredWidth(30);
            TablaEmpleado.getColumnModel().getColumn(8).setMaxWidth(30);
        }

        background.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 620, 340));

        bttLimpiar.setBackground(new java.awt.Color(102, 0, 102));
        bttLimpiar.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        bttLimpiar.setForeground(new java.awt.Color(204, 204, 204));
        bttLimpiar.setText("Limpiar");
        bttLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttLimpiarActionPerformed(evt);
            }
        });
        background.add(bttLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 110, 30));

        jta_Empleado.setBackground(new java.awt.Color(235, 235, 235));
        jta_Empleado.setColumns(20);
        jta_Empleado.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jta_Empleado.setForeground(new java.awt.Color(0, 0, 0));
        jta_Empleado.setRows(5);
        jta_Empleado.setSelectedTextColor(new java.awt.Color(51, 51, 51));
        jta_Empleado.setSelectionColor(new java.awt.Color(204, 204, 255));
        jScrollPane3.setViewportView(jta_Empleado);

        background.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, 580, 50));

        txEdad.setBackground(new java.awt.Color(255, 255, 255));
        txEdad.setForeground(new java.awt.Color(0, 0, 0));
        txEdad.setBorder(null);
        txEdad.setSelectionColor(new java.awt.Color(204, 204, 255));
        background.add(txEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 183, -1));

        lbEdad.setBackground(new java.awt.Color(255, 255, 255));
        lbEdad.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbEdad.setForeground(new java.awt.Color(51, 0, 51));
        lbEdad.setText("Edad:");
        background.add(lbEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        lbApellido.setBackground(new java.awt.Color(255, 255, 255));
        lbApellido.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbApellido.setForeground(new java.awt.Color(51, 0, 51));
        lbApellido.setText("Apellido:");
        background.add(lbApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        txApellido.setBackground(new java.awt.Color(255, 255, 255));
        txApellido.setForeground(new java.awt.Color(0, 0, 0));
        txApellido.setBorder(null);
        txApellido.setSelectionColor(new java.awt.Color(204, 204, 255));
        background.add(txApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 183, -1));

        lbPuesto.setBackground(new java.awt.Color(255, 255, 255));
        lbPuesto.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbPuesto.setForeground(new java.awt.Color(51, 0, 51));
        lbPuesto.setText("Puesto:");
        background.add(lbPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, -1, -1));

        lbSalario.setBackground(new java.awt.Color(255, 255, 255));
        lbSalario.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbSalario.setForeground(new java.awt.Color(51, 0, 51));
        lbSalario.setText("Salario:");
        background.add(lbSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        txSalario.setBackground(new java.awt.Color(255, 255, 255));
        txSalario.setForeground(new java.awt.Color(0, 0, 0));
        txSalario.setBorder(null);
        txSalario.setSelectionColor(new java.awt.Color(204, 204, 255));
        background.add(txSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 183, -1));

        lbID.setBackground(new java.awt.Color(255, 255, 255));
        lbID.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbID.setForeground(new java.awt.Color(51, 0, 51));
        lbID.setText("Id:");
        background.add(lbID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        lbCodID.setBackground(new java.awt.Color(255, 255, 255));
        lbCodID.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbCodID.setForeground(new java.awt.Color(51, 0, 51));
        background.add(lbCodID, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 30, 20));

        cboxPuesto.setBackground(new java.awt.Color(255, 255, 255));
        cboxPuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-----------", "Cajero", "Vendedor", "Despachador" }));
        cboxPuesto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboxPuestoItemStateChanged(evt);
            }
        });
        cboxPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxPuestoActionPerformed(evt);
            }
        });
        background.add(cboxPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, -1, -1));
        background.add(sTelefono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 161, 20));
        background.add(sTelefono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, 161, 20));
        background.add(sDPI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 161, 15));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttReporteActionPerformed
        ab_Empleado.AbrirURL(ab_Empleado.Reporte());
        
    }//GEN-LAST:event_bttReporteActionPerformed

    private void bttAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAgregar1ActionPerformed
        
        if (txCodigo.getText().isEmpty() || txSalario.getText().isEmpty() ||
            cboxPuesto.getSelectedIndex() == 0 || txNombre.getText().isEmpty() || txApellido.getText().isEmpty() ||
            txDPI.getText().isEmpty() || txDireccion.getText().isEmpty() || txEdad.getText().isEmpty() ||
            txTelefono.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Porfavor, ingrese / seleccione todos los campos");
        }
        else
        {
            Empleado e = new Empleado(parseInt(txCodigo.getText()), parseInt(lbCodID.getText()), 
                                      parseDouble(txSalario.getText()), cboxPuesto.getSelectedItem().toString(), 
                                      txNombre.getText(), txApellido.getText(), txDPI.getText(), 
                                      txDireccion.getText(), txEdad.getText(), txTelefono.getText());

            
            if (ab_Empleado.A_InsertarEmpleado(e)){
                DefaultTableModel modelo = (DefaultTableModel) TablaEmpleado.getModel();
                Object[] fila = new Object[10];
                fila[0] = e.getCodigo();
                fila[1] = e.getNombre();
                fila[2] = e.getApellido();
                fila[3] = e.getDPI();
                fila[4] = e.getDireccion();
                fila[5] = e.getEdad();
                fila[6] = e.getTelefono();
                fila[7] = e.getSalario();
                fila[8] = e.getID();
                fila[9] = e.getPuesto();
                
                modelo.addRow(fila);
            }
            limpiar();
        }
    }//GEN-LAST:event_bttAgregar1ActionPerformed

    private void bttModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttModificar1ActionPerformed
        if (txCodigo.getText().isEmpty() || txSalario.getText().isEmpty() ||
            cboxPuesto.getSelectedIndex() == 0 || txNombre.getText().isEmpty() || txApellido.getText().isEmpty() ||
            txDPI.getText().isEmpty() || txDireccion.getText().isEmpty() || txEdad.getText().isEmpty() ||
            txTelefono.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Porfavor, Ingrese todos los campos");
        }
        else{
            Empleado e = new Empleado(parseInt(txCodigo.getText()), parseInt(lbCodID.getText()), 
                                      parseDouble(txSalario.getText()), cboxPuesto.getSelectedItem().toString(), 
                                      txNombre.getText(), txApellido.getText(), txDPI.getText(), 
                                      txDireccion.getText(), txEdad.getText(), txTelefono.getText());
            
            if (ab_Empleado.A_ModificarEmpleado(e)){
                int i = ab_Empleado.VerificarEmpleado(e);
                
                TablaEmpleado.setValueAt(e.getNombre(), i, 1);
                TablaEmpleado.setValueAt(e.getApellido(), i, 2);
                TablaEmpleado.setValueAt(e.getDPI(), i, 3);
                TablaEmpleado.setValueAt(e.getDireccion(), i, 4);
                TablaEmpleado.setValueAt(e.getEdad(), i, 5);
                TablaEmpleado.setValueAt(e.getTelefono(), i, 6);
                TablaEmpleado.setValueAt(e.getSalario(), i, 7);
                TablaEmpleado.setValueAt(e.getID(), i, 8);
                TablaEmpleado.setValueAt(e.getPuesto(), i, 9);
                
                limpiar();
            }
        }
    }//GEN-LAST:event_bttModificar1ActionPerformed

    private void bttEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttEliminar1ActionPerformed
        if (txCodigo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Porfavor, ingrese código de empleado que desea eliminar");
        }
        else{
            Empleado e = new Empleado();
            e.setCodigo(parseInt(txCodigo.getText()));
             
            if (ab_Empleado.VerificarEmpleado(e) != -1){
                
                int op = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar al empleado con código " + e.getCodigo() + "?");
                if (op == 0){   
                    int i = ab_Empleado.VerificarEmpleado(e);
                    DefaultTableModel modelo = (DefaultTableModel) TablaEmpleado.getModel();
                    modelo.removeRow(i);
                    limpiar();   
                    ab_Empleado.A_EliminarEmpleado(e);
                }
            }
        }
    }//GEN-LAST:event_bttEliminar1ActionPerformed

    private void bttGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttGuardarActionPerformed
        try {
            ab_Empleado.GuardarA_Empleado();
        } catch (IOException ex) {
            Logger.getLogger(F_Empleado3597.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bttGuardarActionPerformed

    private void bttBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttBuscarActionPerformed
        if (txCodigo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Porfavor, ingrese código de empleado");
        }
        else
        {
             Empleado e = new Empleado();
             e.setCodigo(parseInt(txCodigo.getText()));
             
            if (ab_Empleado.VerificarEmpleado(e) != -1){
                
                int i = ab_Empleado.VerificarEmpleado(e);
                E = ab_Empleado.A_inv();

                txSalario.setText(Double.toString(E.get(i).getSalario()));
                cboxPuesto.setSelectedIndex(ab_Empleado.VerificarPuesto(e));
                lbCodID.setText(Integer.toString(E.get(i).getID()));
                txNombre.setText(E.get(i).getNombre());
                txApellido.setText(E.get(i).getApellido());
                txDPI.setText(E.get(i).getDPI());
                txDireccion.setText(E.get(i).getDireccion());
                txEdad.setText(E.get(i).getEdad());
                txTelefono.setText(E.get(i).getTelefono());
                
                jta_Empleado.setText(E.get(i).toString());
            }
            else{
                JOptionPane.showMessageDialog(null, "Empleado no existente, según código de empleado\n\nPorfavor, inténtelo de nuevo");
                limpiar();
            }
        }
    }//GEN-LAST:event_bttBuscarActionPerformed

    private void bttLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_bttLimpiarActionPerformed

    private void cboxPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxPuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxPuestoActionPerformed

    private void cboxPuestoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboxPuestoItemStateChanged
        lbCodID.setText(Integer.toString(ab_Empleado.CodigoContador(cboxPuesto.getSelectedItem().toString())));
    }//GEN-LAST:event_cboxPuestoItemStateChanged

    private void limpiar(){   
        jta_Empleado.setText("");
        txCodigo.setText("");
        txSalario.setText("");
        cboxPuesto.setSelectedIndex(0);
        lbCodID.setText(null);
        txNombre.setText("");
        txApellido.setText("");
        txDPI.setText("");
        txDireccion.setText("");
        txEdad.setText("");
        txTelefono.setText("");
        
        txCodigo.requestFocus();
    }
    
    private void TableData(){
        if (ab_Empleado.A_inv() != null){
            E = ab_Empleado.A_inv();
             for (int o = 0; o < E.size(); o++) {
                DefaultTableModel modelo = (DefaultTableModel) TablaEmpleado.getModel();
                Object[] fila = new Object[10];
                fila[0] = E.get(o).getCodigo();
                fila[1] = E.get(o).getNombre();
                fila[2] = E.get(o).getApellido();
                fila[3] = E.get(o).getDPI();
                fila[4] = E.get(o).getDireccion();
                fila[5] = E.get(o).getEdad();
                fila[6] = E.get(o).getTelefono();
                fila[7] = E.get(o).getSalario();
                fila[8] = E.get(o).getID();
                fila[9] = E.get(o).getPuesto();
                
                modelo.addRow(fila); 
            }              
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_Empleado3597.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_Empleado3597.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_Empleado3597.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_Empleado3597.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_Empleado3597().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaEmpleado;
    private javax.swing.JPanel background;
    private javax.swing.JButton bttAgregar1;
    private javax.swing.JButton bttBuscar;
    private javax.swing.JButton bttEliminar1;
    private javax.swing.JButton bttGuardar;
    private javax.swing.JButton bttLimpiar;
    private javax.swing.JButton bttModificar1;
    private javax.swing.JButton bttReporte;
    private javax.swing.JComboBox<String> cboxPuesto;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jta_Empleado;
    private javax.swing.JLabel lbApellido;
    private javax.swing.JLabel lbCodID;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbDPI;
    private javax.swing.JLabel lbDireccion;
    private javax.swing.JLabel lbEdad;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbPuesto;
    private javax.swing.JLabel lbSalario;
    private javax.swing.JLabel lbTelefono;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JSeparator sCodigo;
    private javax.swing.JSeparator sDPI;
    private javax.swing.JSeparator sDPI1;
    private javax.swing.JSeparator sDireccion;
    private javax.swing.JSeparator sNombre;
    private javax.swing.JSeparator sTelefono;
    private javax.swing.JSeparator sTelefono1;
    private javax.swing.JSeparator sTelefono2;
    private javax.swing.JTextField txApellido;
    private javax.swing.JTextField txCodigo;
    private javax.swing.JTextField txDPI;
    private javax.swing.JTextField txDireccion;
    private javax.swing.JTextField txEdad;
    private javax.swing.JTextField txNombre;
    private javax.swing.JTextField txSalario;
    private javax.swing.JTextField txTelefono;
    // End of variables declaration//GEN-END:variables

}
