
package Vista;

import Controlador.AB_Proveedor3597;
import Modelo.Proveedor_3597;
import java.io.IOException;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class F_Proveedor_3597 extends javax.swing.JFrame {


    private ArrayList<Proveedor_3597> P = new ArrayList();
    AB_Proveedor3597 ab_Proveedor3597 = new AB_Proveedor3597();
            
    /** Creates new form F_Proveedor_3597 */
    public F_Proveedor_3597(){
        initComponents();
        
        txCodigo.requestFocus();
        
        ab_Proveedor3597.A_CrearProveedor();
        try {
            ab_Proveedor3597.SalvarA_Proveedor();
        } catch (IOException | ClassNotFoundException ex) {
            ex.printStackTrace();
        }
        
        TableData();
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        lbTitle = new javax.swing.JLabel();
        lbCodigo = new javax.swing.JLabel();
        txCodigo = new javax.swing.JTextField();
        sCodigo = new javax.swing.JSeparator();
        lbNombre = new javax.swing.JLabel();
        txNombre = new javax.swing.JTextField();
        sNombre = new javax.swing.JSeparator();
        lbNIT = new javax.swing.JLabel();
        txNIT = new javax.swing.JTextField();
        sNIT = new javax.swing.JSeparator();
        lbDireccion = new javax.swing.JLabel();
        txDireccion = new javax.swing.JTextField();
        sDireccion = new javax.swing.JSeparator();
        lbTelefono = new javax.swing.JLabel();
        txTelefono = new javax.swing.JTextField();
        sTelefono = new javax.swing.JSeparator();
        bttReporte = new javax.swing.JButton();
        bttBuscar = new javax.swing.JButton();
        bttGuardar = new javax.swing.JButton();
        bttAgregar1 = new javax.swing.JButton();
        bttModificar1 = new javax.swing.JButton();
        bttEliminar1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaProveedor = new javax.swing.JTable();
        bttLimpiar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jta_Prov = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        setLocationByPlatform(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(255, 255, 255));
        background.setForeground(new java.awt.Color(255, 255, 255));
        background.setMinimumSize(new java.awt.Dimension(700, 700));
        background.setPreferredSize(new java.awt.Dimension(700, 700));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbTitle.setBackground(new java.awt.Color(255, 255, 255));
        lbTitle.setFont(new java.awt.Font("Ebrima", 1, 30)); // NOI18N
        lbTitle.setForeground(new java.awt.Color(51, 0, 51));
        lbTitle.setText("Proveedor");
        background.add(lbTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 150, 40));

        lbCodigo.setBackground(new java.awt.Color(255, 255, 255));
        lbCodigo.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbCodigo.setForeground(new java.awt.Color(51, 0, 51));
        lbCodigo.setText("Código: ");
        background.add(lbCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        txCodigo.setBackground(new java.awt.Color(255, 255, 255));
        txCodigo.setForeground(new java.awt.Color(0, 0, 0));
        txCodigo.setBorder(null);
        txCodigo.setSelectionColor(new java.awt.Color(204, 204, 255));
        background.add(txCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 183, -1));
        background.add(sCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 160, 15));

        lbNombre.setBackground(new java.awt.Color(255, 255, 255));
        lbNombre.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbNombre.setForeground(new java.awt.Color(51, 0, 51));
        lbNombre.setText("Nombre:");
        background.add(lbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        txNombre.setBackground(new java.awt.Color(255, 255, 255));
        txNombre.setForeground(new java.awt.Color(0, 0, 0));
        txNombre.setBorder(null);
        txNombre.setSelectionColor(new java.awt.Color(204, 204, 255));
        background.add(txNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 183, -1));
        background.add(sNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 161, 15));

        lbNIT.setBackground(new java.awt.Color(255, 255, 255));
        lbNIT.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbNIT.setForeground(new java.awt.Color(51, 0, 51));
        lbNIT.setText("NIT: ");
        background.add(lbNIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        txNIT.setBackground(new java.awt.Color(255, 255, 255));
        txNIT.setForeground(new java.awt.Color(0, 0, 0));
        txNIT.setBorder(null);
        txNIT.setSelectionColor(new java.awt.Color(204, 204, 255));
        background.add(txNIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 183, -1));
        background.add(sNIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 161, 15));

        lbDireccion.setBackground(new java.awt.Color(255, 255, 255));
        lbDireccion.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbDireccion.setForeground(new java.awt.Color(51, 0, 51));
        lbDireccion.setText("Dirección:");
        background.add(lbDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        txDireccion.setBackground(new java.awt.Color(255, 255, 255));
        txDireccion.setForeground(new java.awt.Color(0, 0, 0));
        txDireccion.setBorder(null);
        txDireccion.setSelectionColor(new java.awt.Color(204, 204, 255));
        background.add(txDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 183, -1));
        background.add(sDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 161, 15));

        lbTelefono.setBackground(new java.awt.Color(255, 255, 255));
        lbTelefono.setFont(new java.awt.Font("Ebrima", 1, 14)); // NOI18N
        lbTelefono.setForeground(new java.awt.Color(51, 0, 51));
        lbTelefono.setText("Teléfono:");
        background.add(lbTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        txTelefono.setBackground(new java.awt.Color(255, 255, 255));
        txTelefono.setForeground(new java.awt.Color(0, 0, 0));
        txTelefono.setBorder(null);
        txTelefono.setSelectionColor(new java.awt.Color(204, 204, 255));
        background.add(txTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 183, -1));
        background.add(sTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 161, 20));

        bttReporte.setBackground(new java.awt.Color(102, 0, 102));
        bttReporte.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        bttReporte.setForeground(new java.awt.Color(204, 204, 204));
        bttReporte.setText("Reporte");
        bttReporte.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttReporteActionPerformed(evt);
            }
        });
        background.add(bttReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 110, 30));

        bttBuscar.setBackground(new java.awt.Color(102, 0, 102));
        bttBuscar.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        bttBuscar.setForeground(new java.awt.Color(204, 204, 204));
        bttBuscar.setText("Buscar");
        bttBuscar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttBuscarActionPerformed(evt);
            }
        });
        background.add(bttBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 110, 30));

        bttGuardar.setBackground(new java.awt.Color(153, 0, 0));
        bttGuardar.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        bttGuardar.setForeground(new java.awt.Color(204, 204, 204));
        bttGuardar.setText("GUARDAR CAMBIOS");
        bttGuardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttGuardarActionPerformed(evt);
            }
        });
        background.add(bttGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 30, 140, 30));

        bttAgregar1.setBackground(new java.awt.Color(102, 0, 102));
        bttAgregar1.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        bttAgregar1.setForeground(new java.awt.Color(204, 204, 204));
        bttAgregar1.setText("Agregar");
        bttAgregar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttAgregar1ActionPerformed(evt);
            }
        });
        background.add(bttAgregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, 110, 30));

        bttModificar1.setBackground(new java.awt.Color(102, 0, 102));
        bttModificar1.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        bttModificar1.setForeground(new java.awt.Color(204, 204, 204));
        bttModificar1.setText("Modificar");
        bttModificar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttModificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttModificar1ActionPerformed(evt);
            }
        });
        background.add(bttModificar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 110, 30));

        bttEliminar1.setBackground(new java.awt.Color(102, 0, 102));
        bttEliminar1.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        bttEliminar1.setForeground(new java.awt.Color(204, 204, 204));
        bttEliminar1.setText("Eliminar");
        bttEliminar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttEliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttEliminar1ActionPerformed(evt);
            }
        });
        background.add(bttEliminar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 390, 110, 30));

        TablaProveedor.setBackground(new java.awt.Color(255, 255, 255));
        TablaProveedor.setFont(new java.awt.Font("Ebrima", 0, 12)); // NOI18N
        TablaProveedor.setForeground(new java.awt.Color(51, 0, 51));
        TablaProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod", "Nombre", "NIT", "Dirección", "Teléfono"
            }
        ));
        TablaProveedor.setGridColor(new java.awt.Color(0, 0, 0));
        TablaProveedor.setSelectionBackground(new java.awt.Color(102, 0, 102));
        TablaProveedor.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(TablaProveedor);
        if (TablaProveedor.getColumnModel().getColumnCount() > 0) {
            TablaProveedor.getColumnModel().getColumn(0).setMinWidth(30);
            TablaProveedor.getColumnModel().getColumn(0).setPreferredWidth(30);
            TablaProveedor.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        background.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 480, 290));

        bttLimpiar.setBackground(new java.awt.Color(102, 0, 102));
        bttLimpiar.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        bttLimpiar.setForeground(new java.awt.Color(204, 204, 204));
        bttLimpiar.setText("Limpiar");
        bttLimpiar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bttLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttLimpiarActionPerformed(evt);
            }
        });
        background.add(bttLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 30, 110, 30));

        jta_Prov.setBackground(new java.awt.Color(235, 235, 235));
        jta_Prov.setColumns(20);
        jta_Prov.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jta_Prov.setForeground(new java.awt.Color(0, 0, 0));
        jta_Prov.setRows(5);
        jta_Prov.setSelectedTextColor(new java.awt.Color(51, 51, 51));
        jta_Prov.setSelectionColor(new java.awt.Color(204, 204, 255));
        jScrollPane3.setViewportView(jta_Prov);

        background.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 580, 50));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttReporteActionPerformed
        ab_Proveedor3597.AbrirURL(ab_Proveedor3597.Reporte());
    }//GEN-LAST:event_bttReporteActionPerformed

    private void bttAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttAgregar1ActionPerformed
        
        if (txCodigo.getText().isEmpty() || txNombre.getText().isEmpty() || 
            txNIT.getText().isEmpty() || txDireccion.getText().isEmpty() ||
            txTelefono.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Porfavor, ingrese todos los campos");
        }
        else
        {
            Proveedor_3597 p = new Proveedor_3597(parseInt(txCodigo.getText()),
                                                  txNombre.getText(),
                                                  txNIT.getText(),
                                                  txDireccion.getText(),
                                                  txTelefono.getText());
            
            if (ab_Proveedor3597.A_InsertarProveedor(p)){
                DefaultTableModel modelo = (DefaultTableModel) TablaProveedor.getModel();
                Object[] fila = new Object[5];
                fila[0] = p.getCodigo();
                fila[1] = p.getNombre();
                fila[2] = p.getNIT();
                fila[3] = p.getDirección();
                fila[4] = p.getTelefono();
                modelo.addRow(fila);
                
                limpiar();
            }
        }
    }//GEN-LAST:event_bttAgregar1ActionPerformed

    private void bttModificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttModificar1ActionPerformed
        if (txCodigo.getText().isEmpty() || txNombre.getText().isEmpty() || 
            txNIT.getText().isEmpty() || txDireccion.getText().isEmpty() ||
            txTelefono.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Porfavor, Ingrese todos los campos");
        }
        else{
            Proveedor_3597 p = new Proveedor_3597(parseInt(txCodigo.getText()),
                                                  txNombre.getText(),
                                                  txNIT.getText(),
                                                  txDireccion.getText(),
                                                  txTelefono.getText());
            
            if (ab_Proveedor3597.A_ModificarProveedor(p)){
                int i = ab_Proveedor3597.VerificarProveedor(p);
                
                TablaProveedor.setValueAt(p.getNombre(), i, 1);
                TablaProveedor.setValueAt(p.getNIT(), i, 2);
                TablaProveedor.setValueAt(p.getDirección(), i, 3);
                TablaProveedor.setValueAt(p.getTelefono(), i, 4);
                
                limpiar();
            }
        }
    }//GEN-LAST:event_bttModificar1ActionPerformed

    private void bttEliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttEliminar1ActionPerformed
        if (txCodigo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Porfavor, ingrese código de proveedor que desea eliminar");
        }
        else{
            Proveedor_3597 p = new Proveedor_3597();
            p.setCodigo(parseInt(txCodigo.getText()));
            
            int i = ab_Proveedor3597.VerificarProveedor(p);
            if (ab_Proveedor3597.A_EliminarProveedor(p)){
                DefaultTableModel modelo = (DefaultTableModel) TablaProveedor.getModel();
                modelo.removeRow(i);
                limpiar();
            }
        }
    }//GEN-LAST:event_bttEliminar1ActionPerformed

    private void bttGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttGuardarActionPerformed
        try {
            ab_Proveedor3597.GuardarA_Proveedor();
        } catch (IOException ex) {
            Logger.getLogger(F_Proveedor_3597.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bttGuardarActionPerformed

    private void bttBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttBuscarActionPerformed
        if (txCodigo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Porfavor, ingrese código de proveedor");
        }
        else
        {
            Proveedor_3597 p = new Proveedor_3597();
            p.setCodigo(parseInt(txCodigo.getText()));
            
            if (ab_Proveedor3597.VerificarProveedor(p) != -1){
                
                int i = ab_Proveedor3597.VerificarProveedor(p);
                P = ab_Proveedor3597.A_inv();

                txNombre.setText(P.get(i).getNombre());
                txNIT.setText(P.get(i).getNIT());
                txDireccion.setText(P.get(i).getDirección());
                txTelefono.setText(P.get(i).getTelefono());
                
                jta_Prov.setText(P.get(i).toString());
            }
            else{
                JOptionPane.showMessageDialog(null, "Proveedor no existente, según código de proveedor\n\nPorfavor, inténtelo de nuevo");
                limpiar();
            }
        }
    }//GEN-LAST:event_bttBuscarActionPerformed

    private void bttLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttLimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_bttLimpiarActionPerformed

    private void limpiar(){   
        jta_Prov.setText("");
        txCodigo.setText("");
        txNombre.setText("");
        txNIT.setText("");
        txDireccion.setText("");
        txTelefono.setText("");
        
        txCodigo.requestFocus();
    }
    
    private void TableData(){
        if (ab_Proveedor3597.A_inv() != null){
            P = ab_Proveedor3597.A_inv();
             for (int o = 0; o < P.size(); o++) {
                DefaultTableModel modelo = (DefaultTableModel) TablaProveedor.getModel();
                Object[] fila = new Object[5];
                fila[0] = P.get(o).getCodigo();
                fila[1] = P.get(o).getNombre();
                fila[2] = P.get(o).getNIT();
                fila[3] = P.get(o).getDirección();
                fila[4] = P.get(o).getTelefono();
                modelo.addRow(fila); 
            }              
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_Proveedor_3597.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_Proveedor_3597.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_Proveedor_3597.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_Proveedor_3597.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_Proveedor_3597().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaProveedor;
    private javax.swing.JPanel background;
    private javax.swing.JButton bttAgregar1;
    private javax.swing.JButton bttBuscar;
    private javax.swing.JButton bttEliminar1;
    private javax.swing.JButton bttGuardar;
    private javax.swing.JButton bttLimpiar;
    private javax.swing.JButton bttModificar1;
    private javax.swing.JButton bttReporte;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jta_Prov;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JLabel lbDireccion;
    private javax.swing.JLabel lbNIT;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbTelefono;
    private javax.swing.JLabel lbTitle;
    private javax.swing.JSeparator sCodigo;
    private javax.swing.JSeparator sDireccion;
    private javax.swing.JSeparator sNIT;
    private javax.swing.JSeparator sNombre;
    private javax.swing.JSeparator sTelefono;
    private javax.swing.JTextField txCodigo;
    private javax.swing.JTextField txDireccion;
    private javax.swing.JTextField txNIT;
    private javax.swing.JTextField txNombre;
    private javax.swing.JTextField txTelefono;
    // End of variables declaration//GEN-END:variables

}
